const SHOW_ALERT_MODAL = 'Global/SHOW_ALERT_MODAL';
const DISMISS_ALERT_MODAL = 'Global/DISMISS_ALERT_MODAL';

const SHOW_CONFIRM_MODAL = 'Global/SHOW_CONFIRM_MODAL';
const DISMISS_CONFIRM_MODAL = 'Global/DISMISS_CONFIRM_MODAL';

const SHOW_ERROR_MODAL = 'Global/SHOW_ERROR_MODAL';
const DISMISS_ERROR_MODAL = 'Global/DISMISS_ERROR_MODAL';

const SHOW_TOP_LOADING_BAR = 'Global/SHOW_TOP_LOADING_BAR';
const DISMISS_TOP_LOADING_BAR = 'Global/DISMISS_TOP_LOADING_BAR';

export default {
    SHOW_ALERT_MODAL,
    DISMISS_ALERT_MODAL,
    SHOW_CONFIRM_MODAL,
    DISMISS_CONFIRM_MODAL,
    SHOW_ERROR_MODAL,
    DISMISS_ERROR_MODAL,
    SHOW_TOP_LOADING_BAR,
    DISMISS_TOP_LOADING_BAR,
};
